################################################################################
#
# [ Event Streaming Application 기본설정 ]
#
################################################################################

################################################################################
# [ 공통 ] 
################################################################################ 
project:
  name: cooltime-event-service

###########################################################################
### Application 설정 
###########################################################################
application:
  # CORS 허용 도메인 #
  cors: 
    allowed-origin:
    - http://cooltime.io
    - https://cooltime.io

################################################################################
# MSA service properties
###########################################################################
service:
  name: Event Streaming
  code: ES
  description: Cooltime Event Service Implementation
  swagger:
    api-response:
      enabled: true

################################################################################
# Servlet config
################################################################################ 
server:
  id: ${HOSTNAME:local}
  port: 8080
  servlet:
    session:
      cookie:
        http-only: true


################################################################################
# Spring-boot config  
################################################################################
spring:
  webflux:
    base-path: 
  autoconfigure:
    exclude: 
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration #일반 디비 설정이 아니므로 자동 설정에서 제외
  data:
################################################################################
# redis settings
    redis:
      host: 127.0.0.1
      port: 6379
      #password: ENC(OgTocaLQCQzzNfH9yLo1Gg==)
      #sentinel:
        #password: ENC(Brf5qI/5o8OIKwBtxVHQXw==)
        #master: datapost
        #nodes: 127.0.0.1:26379

################################################################################
# 보안 설정
  security:
    ### 권한별 접속 경로 설정 ###
    access:
      free:
      - /
      - /favicon.ico
      - /swagger/**
      - /swagger-ui/**
    
    ### OIDC 연동 설정 ###
    realm: bluebears
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://kc.bluebears.co.kr/realms/${spring.security.realm}

################################################################################
# Property encryptor  propperties
################################################################################
jasypt:
  encryptor:
    password: ${ENCRYPTOR_PROFILE}

################################################################################    
# Log properties
################################################################################
logging:
  module: streaming
  level:   
    root: info
    lombok: info
    springfox: info
    org:
      springframework: info
      apache: error
      kafka: info
      jsoup: info
      owasp:
        esapi: info
    com:
      ulisesbocchio: error
      zaxxer: info
      github: debug
  file:
    name: ${app.home:.}/logs/${logging.module}/${server.id}/${logging.module}-service.log
  pattern:
    console: "%d{HH:mm:ss.SSS} %clr(${LOG_LEVEL_PATTERN:-%5p}) %-15logger{0} %msg%n"
    file: "%d{HH:mm:ss.SSS} %-5level %-15logger{0} %msg%n"
  logback:
    rollingpolicy:
      file-name-pattern: ${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz 
      max-file-size: 50MB
      max-history: 30


###########################################################################
### Swagger 설정 
###########################################################################
springdoc:
  swagger-ui:
    use-root-path: true
    path: /swagger/index.html
    tags-sorter: alpha
    operations-sorter: alpha
    urls-primary-name: open-api
  api-docs:
    path: /swagger/docs
    groups:
      enabled: true
  cache:
    disabled: true
  api-info:
    servers:
      - url: http://cooltime.io
        description: front console
    title: template API
    description: Apis for template
    version: 1.0.0
    terms-of-service: http://cooltime.io/termsofservice
    contact:
      name: Administrator
      url: http://cooltime.io
      email: master@cooltime.io
    license:
      name: MIT License
      url: http://cooltime.io/license
