################################################################################
# [ 로컬 서버 프로파일 ]
################################################################################
###########################################################################
### Application config 
application:
  # CORS 허용 도메인 #
  cors: 
    allowed-origin:
    - http://dev.bluebears.co.kr
    - http://localhost

################################################################################
# Server config
server:
  port: 9090

################################################################################
# Spring config
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379