################################################################################
# [ 개발 서버 프로파일 ]
################################################################################

################################################################################    
# Log properties   
logging:
  level:   
    org:
      apache: info

################################################################################
# Spring settings
spring:
  data:
    redis:
      host: 127.0.0.1
      port: 6379